### ISSUE TITLE
Textmate hangs when folding "All Levels" using keyboad

### ISSUE THREAD

**Issue by cr00maui** [textmate/textmate#1137]
Steps:
1) Open a source document of some length. I used /textmate/Frameworks/BundleEditor/src/BundleEditor.mm and duplicated the code (select-all, copy, paste) to make it about 1600 lines. I also wrapped all code in "{ }" to make a large foldable container.
2) keyboard: command-option-0

Expected:
I expected the same performance as option-clicking the main fold icon in the document window. Option-clicking the fold/unfold icon expands the code instantly.

Actual:
Textmate hangs but eventually finishes.

Environment:
MacOS 10.8.5; TextMate 2.0-alpha.9485;
Languages tested: Objective-C++; C#; JavaScript (jQuery)

**Comment by sorbits** [comment]
I am really sorry you had to wait 3 years for this, but it’s resolved in next build.
