### ISSUE TITLE
Lag when saving files via OSX Fuse / Mountee

### ISSUE THREAD

**Issue by jackgringo** [textmate/textmate#855]
Using TextMate version 2.0-alpha.9387

I'm noticing a 1-2 second delay when saving database stored template files via Mountee (http://hellomountee.com/) which uses OSX Fuse to mount these template groups to the file system. On hitting save, the current file icon in the drawer will remain opaque for this 1-2 seconds, with the temp file e.g. ~main.css alongside.

This was pretty seamless with TM1, so thought I should flag it up.

**Comment by sorbits** [comment]
If this is still an issue then please contact support to help you with troubleshooting: https://macromates.com/support
